export type Technology = {
  id: string;
  name: string;
  description: string;
  icon?: string;
  color: string;
  category: string;
  incompatibleWith?: string[];
};

export type Category = {
  id: string;
  name: string;
  description: string;
  singleSelect?: boolean;
  technologies: Technology[];
};

export const categories: Category[] = [
  {
    id: "frontend",
    name: "Web Frontend",
    description: "Choose your frontend framework",
    singleSelect: true,
    technologies: [
      {
        id: "tanstack",
        name: "TanStack",
        description: "Modern type-safe router for React",
        icon: "https://tanstack.com/favicon.ico",
        color: "#FFA171",
        category: "frontend",
      },
      {
        id: "react-router",
        name: "React Router",
        description: "Declarative routing for React",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/reactrouter/reactrouter-original.svg",
        color: "#CA4245",
        category: "frontend",
      },
      {
        id: "nextjs",
        name: "Next.js",
        description: "React framework with hybrid rendering",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
        color: "#999999",
        category: "frontend",
        incompatibleWith: ["vite", "nuxt", "astro"],
      },
      {
        id: "nuxt",
        name: "Nuxt",
        description: "Vue full-stack framework (SSR, SSG, hybrid)",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nuxt/nuxt-original.svg",
        color: "#00DC82",
        category: "frontend",
        incompatibleWith: ["nextjs", "react-router", "tanstack"],
      },
      {
        id: "svelte",
        name: "Svelte",
        description: "Cybernetically enhanced web apps",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg",
        color: "#FF3E00",
        category: "frontend",
      },
      {
        id: "solid",
        name: "Solid",
        description: "Simple and performant reactivity",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/solidjs/solidjs-original.svg",
        color: "#2C4F7C",
        category: "frontend",
      },
      {
        id: "astro",
        name: "Astro",
        description: "The web framework for content-driven websites",
        icon: "https://astro.build/favicon.svg",
        color: "#E33A90",
        category: "frontend",
        incompatibleWith: ["nextjs"],
      },
      {
        id: "no-frontend",
        name: "No Web Frontend",
        description: "No web-based frontend",
        color: "#666666",
        category: "frontend",
      },
    ],
  },
  {
    id: "native",
    name: "Native Frontend",
    description: "Choose your native mobile framework",
    singleSelect: true,
    technologies: [
      {
        id: "expo-bare",
        name: "Expo + Bare",
        description: "Expo with StyleSheet (no styling library)",
        icon: "https://static.expo.dev/static/favicons/favicon-dark-32x32.png",
        color: "#999999",
        category: "native",
      },
      {
        id: "expo-uniwind",
        name: "Expo + Uniwind",
        description: "Fastest Tailwind bindings for React Native",
        icon: "https://static.expo.dev/static/favicons/favicon-dark-32x32.png",
        color: "#999999",
        category: "native",
      },
      {
        id: "expo-unistyles",
        name: "Expo + Unistyles",
        description: "Expo with Unistyles (type-safe styling)",
        icon: "https://static.expo.dev/static/favicons/favicon-dark-32x32.png",
        color: "#999999",
        category: "native",
      },
      {
        id: "no-native",
        name: "No Native Frontend",
        description: "No native mobile frontend",
        color: "#666666",
        category: "native",
      },
    ],
  },
  {
    id: "backend",
    name: "Backend",
    description: "Choose your backend framework",
    singleSelect: true,
    technologies: [
      {
        id: "hono",
        name: "Hono",
        description: "Ultrafast web framework",
        icon: "https://hono.dev/images/logo.png",
        color: "#FF6B35",
        category: "backend",
      },
      {
        id: "elysia",
        name: "Elysia",
        description: "TypeScript web framework",
        icon: "https://elysiajs.com/assets/elysia.svg",
        color: "#A855F7",
        category: "backend",
      },
      {
        id: "express",
        name: "Express",
        description: "Popular Node.js framework",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
        color: "#999999",
        category: "backend",
      },
      {
        id: "fastify",
        name: "Fastify",
        description: "Fast, low-overhead web framework for Node.js",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastify/fastify-plain.svg",
        color: "#999999",
        category: "backend",
      },
      {
        id: "convex",
        name: "Convex",
        description: "Reactive backend-as-a-service",
        color: "#F97316",
        category: "backend",
      },
      {
        id: "fullstack-nextjs",
        name: "Fullstack Next.js",
        description: "Use Next.js built-in API routes",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
        color: "#999999",
        category: "backend",
        incompatibleWith: ["nuxt", "astro"],
      },
      {
        id: "fullstack-nuxt",
        name: "Fullstack Nuxt",
        description: "Use Nuxt's built-in server routes",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nuxt/nuxt-original.svg",
        color: "#00DC82",
        category: "backend",
        incompatibleWith: ["nextjs", "astro"],
      },
      {
        id: "fullstack-astro",
        name: "Fullstack Astro",
        description: "Use Astro's built-in API routes",
        icon: "https://astro.build/favicon.svg",
        color: "#E33A90",
        category: "backend",
        incompatibleWith: ["nextjs", "nuxt"],
      },
      {
        id: "no-backend",
        name: "No Backend",
        description: "Skip backend integration (frontend only)",
        color: "#666666",
        category: "backend",
      },
    ],
  },
  {
    id: "runtime",
    name: "Runtime",
    description: "Choose your JavaScript runtime",
    singleSelect: true,
    technologies: [
      {
        id: "bun",
        name: "Bun",
        description: "Fast JavaScript runtime & toolkit",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bun/bun-original.svg",
        color: "#FBF0DF",
        category: "runtime",
      },
      {
        id: "nodejs",
        name: "Node.js",
        description: "JavaScript runtime environment",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
        color: "#339933",
        category: "runtime",
      },
      {
        id: "cloudflare-workers",
        name: "Cloudflare Workers",
        description: "Serverless runtime for the edge",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cloudflareworkers/cloudflareworkers-original.svg",
        color: "#F6821F",
        category: "runtime",
      },
      {
        id: "no-runtime",
        name: "No Runtime",
        description: "No specific runtime",
        color: "#666666",
        category: "runtime",
      },
    ],
  },
  {
    id: "api",
    name: "API",
    description: "Choose your API layer",
    singleSelect: true,
    technologies: [
      {
        id: "trpc",
        name: "tRPC",
        description: "End-to-end typesafe APIs",
        icon: "https://trpc.io/img/logo.svg",
        color: "#398CCB",
        category: "api",
      },
      {
        id: "orpc",
        name: "oRPC",
        description: "Typesafe APIs Made Simple",
        color: "#1a1a1a",
        category: "api",
      },
      {
        id: "no-api",
        name: "No API",
        description: "No API layer (API routes disabled)",
        color: "#666666",
        category: "api",
      },
    ],
  },
  {
    id: "database",
    name: "Database",
    description: "Choose your database",
    singleSelect: true,
    technologies: [
      {
        id: "sqlite",
        name: "SQLite",
        description: "File-based SQL database",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg",
        color: "#003B57",
        category: "database",
      },
      {
        id: "postgresql",
        name: "PostgreSQL",
        description: "Advanced SQL database",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
        color: "#4169E1",
        category: "database",
        incompatibleWith: ["mongoose"],
      },
      {
        id: "mysql",
        name: "MySQL",
        description: "Popular relational database",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
        color: "#4479A1",
        category: "database",
        incompatibleWith: ["mongoose"],
      },
      {
        id: "mongodb",
        name: "MongoDB",
        description: "NoSQL document database",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
        color: "#47A248",
        category: "database",
        incompatibleWith: ["drizzle", "prisma"],
      },
      {
        id: "no-database",
        name: "No Database",
        description: "Skip database integration",
        color: "#666666",
        category: "database",
      },
    ],
  },
  {
    id: "orm",
    name: "ORM",
    description: "Choose your ORM",
    singleSelect: true,
    technologies: [
      {
        id: "drizzle",
        name: "Drizzle",
        description: "TypeScript ORM",
        icon: "https://orm.drizzle.team/favicon.ico",
        color: "#C5F74F",
        category: "orm",
        incompatibleWith: ["mongodb", "mongoose"],
      },
      {
        id: "prisma",
        name: "Prisma",
        description: "Next-gen ORM",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/prisma/prisma-original.svg",
        color: "#2D3748",
        category: "orm",
        incompatibleWith: ["mongoose"],
      },
      {
        id: "mongoose",
        name: "Mongoose",
        description: "Elegant object modeling for MongoDB",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongoose/mongoose-original.svg",
        color: "#880000",
        category: "orm",
        incompatibleWith: [
          "drizzle",
          "prisma",
          "postgresql",
          "mysql",
          "sqlite",
        ],
      },
      {
        id: "no-orm",
        name: "No ORM",
        description: "Skip ORM integration",
        color: "#666666",
        category: "orm",
      },
    ],
  },
  {
    id: "db-setup",
    name: "DB Setup",
    description: "Choose your database setup",
    singleSelect: true,
    technologies: [
      {
        id: "turso",
        name: "Turso",
        description: "Distributed SQLite with edge replicas (libSQL)",
        icon: "https://turso.tech/favicon.ico",
        color: "#4FF8D2",
        category: "db-setup",
      },
      {
        id: "cloudflare-d1",
        name: "Cloudflare D1",
        description: "Serverless SQLite-compatible database",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cloudflareworkers/cloudflareworkers-original.svg",
        color: "#F6821F",
        category: "db-setup",
      },
      {
        id: "neon",
        name: "Neon Postgres",
        description: "Serverless Postgres with autoscaling and branching",
        icon: "https://neon.com/favicon/favicon.svg",
        color: "#00E599",
        category: "db-setup",
      },
      {
        id: "prisma-postgres",
        name: "Prisma PostgreSQL",
        description: "Managed Postgres via Prisma Data Platform",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/prisma/prisma-original.svg",
        color: "#2D3748",
        category: "db-setup",
      },
      {
        id: "mongodb-atlas",
        name: "MongoDB Atlas",
        description: "Managed MongoDB clusters in the cloud",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg",
        color: "#47A248",
        category: "db-setup",
      },
      {
        id: "supabase",
        name: "Supabase",
        description: "Local Postgres stack via Supabase (Docker required)",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/supabase/supabase-original.svg",
        color: "#3ECF8E",
        category: "db-setup",
      },
      {
        id: "planetscale",
        name: "PlanetScale",
        description: "Postgres & Vitess (MySQL) on NVMe",
        icon: "https://planetscale.com/icon.png",
        color: "#999999",
        category: "db-setup",
      },
      {
        id: "docker-db",
        name: "Docker",
        description: "Run Postgres/MySQL/MongoDB locally via Docker Compose",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-plain.svg",
        color: "#2496ED",
        category: "db-setup",
      },
      {
        id: "no-db-setup",
        name: "No DB Setup",
        description: "Skip database setup",
        color: "#666666",
        category: "db-setup",
      },
    ],
  },
  {
    id: "auth",
    name: "Auth",
    description: "Choose your authentication solution",
    singleSelect: true,
    technologies: [
      {
        id: "better-auth",
        name: "Better-Auth",
        description: "The most comprehensive authentication framework",
        icon: "https://www.better-auth.com/logo.png",
        color: "#999999",
        category: "auth",
      },
      {
        id: "clerk",
        name: "Clerk",
        description: "More than authentication, Complete User Management",
        color: "#6C47FF",
        category: "auth",
      },
      {
        id: "authjs",
        name: "Auth.js",
        description: "Authentication for the Web",
        color: "#999999",
        category: "auth",
      },
      {
        id: "lucia",
        name: "Lucia",
        description: "Simple and flexible auth library",
        color: "#5F57FF",
        category: "auth",
      },
      {
        id: "no-auth",
        name: "No Auth",
        description: "Skip authentication",
        color: "#666666",
        category: "auth",
      },
    ],
  },
  {
    id: "ui",
    name: "UI Library",
    description: "Choose your UI components",
    singleSelect: false,
    technologies: [
      {
        id: "shadcn",
        name: "shadcn/ui",
        description: "Beautifully designed components",
        icon: "https://ui.shadcn.com/favicon.ico",
        color: "#999999",
        category: "ui",
      },
      {
        id: "heroui",
        name: "HeroUI",
        description: "Beautiful, fast and modern React UI library",
        icon: "https://heroui.com/favicon.ico",
        color: "#999999",
        category: "ui",
      },
      {
        id: "radix",
        name: "Radix UI",
        description: "Unstyled, accessible components",
        icon: "https://www.radix-ui.com/favicon.png",
        color: "#999999",
        category: "ui",
      },
      {
        id: "ark-ui",
        name: "Ark UI",
        description: "Headless UI components",
        icon: "https://ark-ui.com/favicon.ico",
        color: "#A855F7",
        category: "ui",
      },
      {
        id: "tailwindcss",
        name: "TailwindCSS",
        description: "Utility-first CSS framework",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg",
        color: "#06B6D4",
        category: "ui",
      },
    ],
  },
  {
    id: "payments",
    name: "Payments",
    description: "Choose your payment solution",
    singleSelect: true,
    technologies: [
      {
        id: "polar",
        name: "Polar",
        description: "Turn your software into a business. 6 lines of code.",
        icon: "https://r2.better-t-stack.dev/icons/polar.svg",
        color: "#0062FF",
        category: "payments",
      },
      {
        id: "stripe",
        name: "Stripe",
        description: "Online payment processing",
        color: "#635BFF",
        category: "payments",
      },
      {
        id: "no-payments",
        name: "No Payments",
        description: "Skip payments integration",
        color: "#666666",
        category: "payments",
      },
    ],
  },
  {
    id: "package-manager",
    name: "Package Manager",
    description: "Choose your package manager",
    singleSelect: true,
    technologies: [
      {
        id: "npm",
        name: "npm",
        description: "Default package manager",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original.svg",
        color: "#CB3837",
        category: "package-manager",
      },
      {
        id: "pnpm",
        name: "pnpm",
        description: "Fast, disk space efficient",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pnpm/pnpm-original.svg",
        color: "#F69220",
        category: "package-manager",
      },
      {
        id: "yarn",
        name: "yarn",
        description: "Fast, reliable, and secure dependency management",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/yarn/yarn-original.svg",
        color: "#2C8EBB",
        category: "package-manager",
      },
      {
        id: "bun-pm",
        name: "bun",
        description: "All-in-one toolkit",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bun/bun-original.svg",
        color: "#FBF0DF",
        category: "package-manager",
      },
    ],
  },
  {
    id: "tooling",
    name: "Tooling",
    description: "Additional development tools",
    singleSelect: false,
    technologies: [
      {
        id: "biome",
        name: "Biome",
        description: "Format, lint, and more",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/biome/biome-original.svg",
        color: "#60A5FA",
        category: "tooling",
      },
      {
        id: "eslint",
        name: "ESLint",
        description: "Pluggable linting utility",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/eslint/eslint-original.svg",
        color: "#4B32C3",
        category: "tooling",
      },
      {
        id: "prettier",
        name: "Prettier",
        description: "Opinionated code formatter",
        icon: "https://prettier.io/icon.png",
        color: "#F7B93E",
        category: "tooling",
      },
      {
        id: "husky",
        name: "Husky",
        description: "Modern native Git hooks made easy",
        color: "#29383D",
        category: "tooling",
      },
      {
        id: "lefthook",
        name: "Lefthook",
        description: "Fast and powerful Git hooks manager",
        color: "#FF4081",
        category: "tooling",
      },
      {
        id: "turborepo",
        name: "Turborepo",
        description: "High-performance build system",
        icon: "https://r2.better-t-stack.dev/icons/turborepo.svg",
        color: "#EF4444",
        category: "tooling",
      },
      {
        id: "typescript",
        name: "TypeScript",
        description: "Typed superset of JavaScript",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
        color: "#3178C6",
        category: "tooling",
      },
    ],
  },
  {
    id: "validation",
    name: "Validation",
    description: "Schema validation libraries",
    singleSelect: false,
    technologies: [
      {
        id: "zod",
        name: "Zod",
        description: "TypeScript-first schema validation",
        icon: "https://zod.dev/logo/logo.png",
        color: "#3068B7",
        category: "validation",
      },
      {
        id: "valibot",
        name: "Valibot",
        description: "Modular and type-safe schema library",
        icon: "https://valibot.dev//icon-16px.png",
        color: "#EEBF41",
        category: "validation",
      },
    ],
  },
  {
    id: "addons",
    name: "Addons",
    description: "Additional features and integrations",
    singleSelect: false,
    technologies: [
      {
        id: "pwa",
        name: "PWA",
        description: "Make your app installable and work offline",
        color: "#5A0FC8",
        category: "addons",
      },
      {
        id: "tauri",
        name: "Tauri",
        description: "Build native desktop apps",
        icon: "https://tauri.app/favicon.svg",
        color: "#999999",
        category: "addons",
      },
      {
        id: "starlight",
        name: "Starlight",
        description: "Build stellar docs with Astro",
        icon: "https://starlight.astro.build/favicon.svg",
        color: "#FFC131",
        category: "addons",
      },
      {
        id: "fumadocs",
        name: "Fumadocs",
        description: "Build excellent documentation site",
        icon: "https://www.fumadocs.dev//icon.png?icon.f741d7a1.png",
        color: "#999999",
        category: "addons",
      },
      {
        id: "ai-sdk",
        name: "AI SDK",
        description: "AI integration using Vercel AI SDK",
        color: "#999999",
        category: "addons",
      },
      {
        id: "dotenv",
        name: "dotenv",
        description: "Environment variable management",
        icon: "https://raw.githubusercontent.com/motdotla/dotenv/master/dotenv.svg",
        color: "#ECD53F",
        category: "addons",
      },
    ],
  },
  {
    id: "git",
    name: "Git",
    description: "Git initialization",
    singleSelect: true,
    technologies: [
      {
        id: "git-init",
        name: "Git",
        description: "Initialize Git repository",
        icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
        color: "#F05032",
        category: "git",
      },
      {
        id: "no-git",
        name: "No Git",
        description: "Skip Git initialization",
        color: "#666666",
        category: "git",
      },
    ],
  },
];

export type Preset = {
  id: string;
  name: string;
  description: string;
  selections: string[];
};

export const presets: Preset[] = [
  {
    id: "most-used",
    name: "Most Used Stack",
    description: "The most popular combination used by developers",
    selections: [
      "nextjs",
      "no-native",
      "fullstack-nextjs",
      "nodejs",
      "trpc",
      "postgresql",
      "drizzle",
      "neon",
      "better-auth",
      "shadcn",
      "no-payments",
      "pnpm",
      "biome",
      "zod",
      "git-init",
    ],
  },
  {
    id: "saas",
    name: "SaaS Starter",
    description: "Perfect for building SaaS applications",
    selections: [
      "nextjs",
      "no-native",
      "fullstack-nextjs",
      "nodejs",
      "trpc",
      "postgresql",
      "prisma",
      "neon",
      "clerk",
      "shadcn",
      "stripe",
      "pnpm",
      "biome",
      "zod",
      "turborepo",
      "git-init",
    ],
  },
  {
    id: "fullstack-react",
    name: "Fullstack React",
    description: "Modern fullstack React setup",
    selections: [
      "tanstack",
      "no-native",
      "hono",
      "bun",
      "trpc",
      "sqlite",
      "drizzle",
      "turso",
      "better-auth",
      "shadcn",
      "no-payments",
      "bun-pm",
      "biome",
      "zod",
      "git-init",
    ],
  },
  {
    id: "edge-first",
    name: "Edge-First",
    description: "Optimized for edge computing",
    selections: [
      "no-native",
      "hono",
      "cloudflare-workers",
      "orpc",
      "sqlite",
      "drizzle",
      "cloudflare-d1",
      "better-auth",
      "shadcn",
      "no-payments",
      "pnpm",
      "biome",
      "zod",
      "git-init",
    ],
  },
  {
    id: "vue-fullstack",
    name: "Vue Fullstack",
    description: "Complete Vue/Nuxt setup",
    selections: [
      "nuxt",
      "no-native",
      "fullstack-nuxt",
      "nodejs",
      "no-api",
      "postgresql",
      "prisma",
      "supabase",
      "authjs",
      "no-payments",
      "pnpm",
      "eslint",
      "prettier",
      "zod",
      "git-init",
    ],
  },
  {
    id: "mobile-first",
    name: "Mobile First",
    description: "React Native with Expo",
    selections: [
      "no-frontend",
      "expo-uniwind",
      "hono",
      "bun",
      "trpc",
      "postgresql",
      "drizzle",
      "neon",
      "better-auth",
      "no-payments",
      "bun-pm",
      "biome",
      "zod",
      "git-init",
    ],
  },
];
